name: "📘 Documentation Update"
description: Request an improvement or fix in documentation
labels: ["documentation"]
body:
  - type: input
    id: page
    attributes:
      label: Page / Section to Update
      description: Which doc page needs improvement?
      placeholder: docs/setup.md
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Suggested Changes
      description: Describe what needs to be added or fixed.
      placeholder: This section is unclear because...
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason / Benefit
      description: Why is this update important?
      placeholder: This will help contributors understand...

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any extra references or links.
