name: "💡 Feature Request"
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: Explain the problem your feature would solve.
      placeholder: The issue I'm facing is...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you want.
      placeholder: I suggest that we...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Mention other approaches you thought of.
      placeholder: Another way to solve this could be...

  - type: textarea
    id: extra
    attributes:
      label: Additional Details
      description: Add references or examples if available.
